### ISSUE TITLE
DataLayer - PageType

### ISSUE THREAD

**Issue by paalsoberg** [magepal/magento1-googletagmanager#15]
Great module guys - currently the pageType comes through the datalayer using Magento page types, e.g. catalog_category_index for category. However Google needs it to follow their naming;

This is from Google;
ecomm_pagetype | Indicates the type of page that the tag is on. Valid values:
* **home** Used on the home page or landing page of your site.
* **searchresults** Used on pages where the results of a user's search are displayed.
* **category** Used on pages that list multiple items within a category, for example a page showing all shoes in a given style.
* **product** Used on individual product pages.cart Used on the cart/basket/checkout page.
* **purchase** Used on the page shown once a user has purchased (and so converted), for example a "Thank You" or confirmation page.
* **other** Used where the page does not fit into the other types of page, for example a "Contact Us" or "About Us" page.

Example usage:

>var google_tag_params = {   ecomm_pagetype: 'searchresults'};

**Comment by grantkemp** [comment]
@paalsoberg  the easiest solution for this - would be to use a lookup table in GTM - using that data. you map that magento page type to the output that you want. 
This is supported without a code change.

**Comment by paalsoberg** [comment]
Cool cheers :)
