### ISSUE TITLE
DataLayer empty on checkout success

### ISSUE THREAD

**Issue by hans2103** [magepal/magento1-googletagmanager#16]
I've noticed that on a success page the datalayer stays empty. This results in no _Conversions data_ in Google Analytics.

https://github.com/magepal/magento1-googletagmanager/blob/ea400d7945d44443aa32f45dea28abcf08e440c2/app/code/local/MagePal/GoogleTagManager/Block/Tm.php#L155

when I do a ```var_dump(!$this->_orderCollection)``` I get an order id. 
I was expecting to get order information 

Therefor I've removed the if-statement around this block and now it works.

Can you reproduce this issue?

**Comment by srenon** [comment]
@hans2103 ....  Take a look at this https://github.com/magepal/magento2-googletagmanager/issues/15 .... This is M2 but seem like the same issue

**Comment by hans2103** [comment]
bump

**Comment by srenon** [comment]
The if statement only caches the collection result so that it does not have to query the DB each time but since $this->getOrderCollection() is only called one it don't offer any benefit.

**Comment by srenon** [comment]
fixed
