### ISSUE TITLE
does not auto append to .gitignore

### ISSUE THREAD

**Issue by alexkoepke** [magepal/magento1-googletagmanager#5]
I have tried adding the following to the composer.json [in my own forked repo ](https://github.com/alexkoepke/magento1-googletagmanager/blob/e4bf0a8e35c60d2ad4f2de6cccbb3d21631983d8/composer.json)but can't seem to get it to auto-append to the .gitignore  any help would be much appreciated.

`"extra": {
        "map": [
            ["app/code/local/MagePal/GoogleTagManager","app/code/local/MagePal/GoogleTagManager"],
            ["app/design/frontend/base/default/layout/magepal_googletagmanager.xml","app/design/frontend/base/default/layout/magepal_googletagmanager.xml"],
            ["app/design/frontend/base/default/template/magepal/googletagmanager","app/design/frontend/base/default/template/magepal/googletagmanager"],
            ["app/etc/modules/MagePal_GoogleTagManager.xml","app/etc/modules/MagePal_GoogleTagManager.xml"]
        ],
        "auto-append-gitignore": true
    }`

@hans2103 only tagging you because you were so kind to get this ball rolling :)

**Comment by alex-koepke** [comment]
Do you need more info to test? @hans2103 do you have any ideas?

**Comment by alexkoepke** [comment]
Yes.

There is also an extra comma at the end of the composer.json that prevents composer from installing so I had to fork.

When I removed it the extension would install but would not auto append to .gitigone with auto-append in both magento compose.json and the fork of this extensions composer.json.
